version: '3.6'

services:
  database:
    restart: always
    container_name: pawb_miniprojeto_database2
    image: postgres:12 # use latest official postgres version
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - "5444:5432"

  backend:
    container_name: pawb_miniprojeto_backend2
    links:
      - database
    restart: always
    build: back/.
    ports:
      - "8081:8080"
    depends_on:
      - database
    volumes:
      - ./back/source:/go/src/api

  frontend:
    container_name: pawb_miniprojeto_frontend2
    links:
      - backend
    restart: always
    build: front/.
    ports:
      - "8082:3000"
    depends_on:
      - backend
    volumes:
      - ./front/source:/app


volumes:
  database-data: # named volumes can be managed easier using docker-compose

