version: '3.6'

services:
  database:
    restart: always
    container_name: pawb_database
    image: postgres:12 # use latest official postgres version
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=apidb
    ports:
      - "5444:5432"

  backend:
    container_name: pawb_backend
    links:
      - database
    restart: always
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - database
    volumes:
      - ./source:/go/src/api

volumes:
  database-data: # named volumes can be managed easier using docker-compose

